In [1]:
# Import necessary PyTorch packages
import torch
import torch.nn as nn
import torch.nn.functional as F

In [23]:
from models.simple import NetC_MNIST

classifier = NetC_MNIST(channels=3)

In [24]:
# Initialize a crossentropy loss instance PyTorch
loss_fn = nn.CrossEntropyLoss()


In [25]:
# Intiliaze a tensor of size 100, 3, 32, 32 filled with -1 values
data = torch.ones((100, 3, 32, 32)) * -1

# Initialize a tensor of size 100 filled with random integers from 0 to 9
target = torch.randint(0, 9, (100,))

In [27]:
data.shape, target.shape

(torch.Size([100, 3, 32, 32]), torch.Size([100]))

In [29]:
output = classifier(data)

In [30]:
output

tensor([[-1.1300e-01,  7.4250e-02,  6.1700e-02,  5.5718e-02, -1.1506e-01,
         -3.6060e-02, -8.5331e-02,  1.1605e-02,  2.1853e-01,  6.5895e-02],
        [-3.1698e-02, -4.4403e-02,  5.7291e-02, -9.4476e-02,  2.0609e-02,
          6.2469e-02,  8.5031e-03,  5.2436e-02,  2.3305e-01,  1.2373e-01],
        [-5.8529e-02,  5.1005e-02,  9.7616e-02, -6.7404e-02,  1.1168e-02,
          1.2670e-03, -7.3874e-02, -4.3440e-02,  1.8123e-01,  5.3787e-02],
        [-2.7388e-02, -1.0760e-02,  6.5633e-02, -6.5326e-02, -5.0581e-02,
         -5.4159e-03, -5.1744e-02,  8.5804e-02,  1.2904e-01,  4.3034e-02],
        [-3.2934e-02, -6.4590e-02,  2.5096e-02, -1.1611e-01, -4.8705e-02,
          3.4599e-03,  4.0598e-02,  7.2518e-02,  7.3025e-02,  9.3094e-02],
        [-1.0579e-01,  5.0917e-02,  7.2105e-02, -3.6344e-03, -1.5186e-02,
          2.1443e-02, -4.2595e-02, -1.2107e-01,  1.7342e-01,  1.9790e-02],
        [-1.0768e-01,  2.5067e-02,  7.2355e-02, -9.1701e-02, -1.5779e-02,
          7.7309e-03, -5.4741e-0

In [28]:
loss_fn(data, target)

RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 1

In [7]:
from attack_models.autoencoders import MNISTAutoencoder as Autoencoder
import torch

atkmodel = Autoencoder().to("cuda")

In [8]:
atkmodel.load_state_dict(torch.load("./checkpoint/lira/lira_mnist_lenet_autoencoder_0.03.pt", map_location="cuda"))

<All keys matched successfully>

In [17]:
import torch

# Assuming you have the data and target tensors
data = torch.randn(64, 3, 32, 32)  # Replace this with your actual data
# target = torch.randint(0, 10, (64,))  # Replace this with your actual target tensor
target = torch.tensor([1,2,3,4])  # Replace this with your actual target tensor

# Get indices where target is equal to 1
indices = (target == 5).nonzero(as_tuple=True)[0]

# Use the indices to select data with target==1
selected_data = data[indices]

# Print the shape of the selected data
print(selected_data.shape)


torch.Size([0, 3, 32, 32])


In [25]:
if len(indices) == 0:
    print('aksdjhaksdh')

aksdjhaksdh


In [15]:
a = torch.tensor([1,2,3])
a[[False, False, False]].shape

torch.Size([0])

In [65]:
import torch


# Create a tensor of size (4, 3, 32, 32)
a = torch.arange(10, dtype=torch.float32, requires_grad=True) # a is a batch of 4 images size 32x32 with 3 channels

# Create another tensor of size (4, 3, 32, 32)
b = torch.arange(10, 20, dtype=torch.float32, requires_grad=True) # b is a batch of 4 images size 32x32 with 3 channels

c = torch.tensor(-11, dtype=torch.float32, requires_grad=True)
c = max(torch.tensor(0.05, requires_grad=False), c)

optimizer = torch.optim.Adam([a, b, c], lr=0.001)
# Compute the L2 distance of a and b and then sum all 4 images
loss = torch.sum(torch.square(a - b)) / 4 + c
loss

tensor(250.0500, grad_fn=<AddBackward0>)

In [67]:
loss.backward()

In [68]:
optimizer.step()

In [66]:
c

tensor(0.0500)

In [69]:
c

tensor(0.0500)

In [59]:
c = torch.tensor(-11, dtype=torch.float32, requires_grad=True)
c = max(0.05, c)
c

0.05

In [115]:
import torch

# Create a list of tensors

a = torch.randint(-4, 4, (2, 3))
b = torch.randint(-4, 4, (2, 3))
c = torch.randint(-4, 4, (2, 3))
d = torch.randint(-4, 4, (2, 3))
e = torch.randint(-4, 4, (2, 3))
f = torch.randint(-4, 4, (2, 3))

ratio = 0.5
grad_list = []
grad_abs_sum_list = []
# Print the result
a.shape, b.shape, c.shape

(torch.Size([2, 3]), torch.Size([2, 3]), torch.Size([2, 3]))

In [116]:
grad_list.append(a.abs().view(-1))
grad_list.append(b.abs().view(-1))
grad_list.append(c.abs().view(-1))
grad_list.append(d.abs().view(-1))
grad_list.append(e.abs().view(-1))
grad_list.append(f.abs().view(-1))
grad_list

[tensor([1, 2, 4, 4, 1, 2]),
 tensor([0, 3, 2, 4, 2, 2]),
 tensor([4, 2, 3, 3, 0, 2]),
 tensor([1, 0, 1, 4, 1, 0]),
 tensor([0, 2, 3, 3, 3, 1]),
 tensor([1, 2, 2, 3, 3, 1])]

In [117]:
grad_abs_sum_list.append(a.abs().view(-1).sum().item())
grad_abs_sum_list.append(b.abs().view(-1).sum().item())
grad_abs_sum_list.append(c.abs().view(-1).sum().item())
grad_abs_sum_list.append(d.abs().view(-1).sum().item())
grad_abs_sum_list.append(e.abs().view(-1).sum().item())
grad_abs_sum_list.append(f.abs().view(-1).sum().item())
grad_abs_sum_list

[14, 13, 14, 7, 12, 12]

In [118]:
grad_list = torch.cat(grad_list)
grad_list

tensor([1, 2, 4, 4, 1, 2, 0, 3, 2, 4, 2, 2, 4, 2, 3, 3, 0, 2, 1, 0, 1, 4, 1, 0,
        0, 2, 3, 3, 3, 1, 1, 2, 2, 3, 3, 1])

In [119]:
_, indices = torch.topk(-1*grad_list, 10)
indices

tensor([ 6, 16, 19, 23, 24, 20, 35,  0, 30, 22])

In [123]:
mask_flat_all_layer = torch.zeros(len(grad_list))
mask_flat_all_layer[indices] = 1.0
mask_flat_all_layer

tensor([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [108]:
torch.topk(-1*grad_list, 10)

torch.return_types.topk(
values=tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1]),
indices=tensor([21, 28,  9, 31,  5, 34,  1,  2, 33, 24]))

In [127]:
gradients_length = len(a.abs().view(-1))
gradients_length

6

In [128]:
percentage_mask_list = []
grad_abs_percentage_list = []

In [2]:
a = torch.tensor([1,2,3,4], dtype=torch.float32)
b = torch.tensor([1,2,3,4], dtype=torch.float32)
c = torch.tensor([1,2,3,4], dtype=torch.float32)
d = torch.tensor([1,2,3,4], dtype=torch.float32)
e = torch.tensor([1,2,3,4], dtype=torch.float32)


In [3]:
t = []
t.append(a)
t.append(b)
t.append(c)
t.append(d)
t.append(e)
t

[tensor([1., 2., 3., 4.]),
 tensor([1., 2., 3., 4.]),
 tensor([1., 2., 3., 4.]),
 tensor([1., 2., 3., 4.]),
 tensor([1., 2., 3., 4.])]

In [5]:
sum(t) / len(t)

tensor([1., 2., 3., 4.])

In [12]:
# Import necessary PyTorch packages
import torch
import torch.nn as nn
import torch.nn.functional as F

import sys

In [32]:
a = torch.tensor([1,2,3,4], dtype=torch.float32, requires_grad=True, device='cuda')
a

tensor([1., 2., 3., 4.], device='cuda:0', requires_grad=True)

In [37]:
t = []
t.append(a)
t.append(a)
sum(t) / len(t)

tensor([1., 2., 3., 4.], device='cuda:0', grad_fn=<DivBackward0>)

In [35]:
b

tensor([1., 2., 3., 4., 1., 2., 3., 4.], device='cuda:0',
       grad_fn=<CatBackward0>)

In [30]:
id(a.cuda())

139785753930352

In [31]:
id(a.cpu())

139785751993280

In [3]:
import torch


a = torch.tensor(range(24)).view(2, 3, 4)
b = torch.tensor(range(24)).view(2, 3, 4)
a, b

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]))

In [12]:
torch.sum(torch.square(a-b), dim=(1, 2))

tensor([0, 0])

In [23]:
# Import necessary PyTorch packages
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

import kornia.augmentation as A

import sys
import random

from utils.backdoor import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD, IMAGENET_MIN, IMAGENET_MAX
from attack_models.autoencoders import ConditionalAutoencoder
from models.resnet_cifar import ResNet18


In [24]:
tgtmodel = ConditionalAutoencoder(n_classes=10, input_dim=32).to("cuda")
model = ResNet18().to("cuda")

prefix = f"/hdd/home/ssd_data/Son/LRBA/saved_models/model_CIFAR10_01.21_16.12.04_cifar10/"
path = prefix + "model_last.pt.tar"
with open(path, "rb") as f:
    checkpoint = torch.load(f, map_location="cuda")
    model.load_state_dict(checkpoint["state_dict"])
    tgtmodel.load_state_dict(checkpoint["tgt_state_dict"])

tgtoptimizer = torch.optim.Adam(tgtmodel.parameters(), lr=0.0002, betas=(0.5, 0.999))

In [25]:
class ProbTransform(torch.nn.Module):
    def __init__(self, f, p=1):
        super(ProbTransform, self).__init__()
        self.f = f
        self.p = p

    def forward(self, x):  # , **kwargs):
        if random.random() < self.p:
            return self.f(x)
        else:
            return x


class PostTensorTransform(torch.nn.Module):
    def __init__(self, opt):
        super(PostTensorTransform, self).__init__()
        self.random_crop = ProbTransform(
            A.RandomCrop((32, 32), padding=5), p=0.8
        )
        self.random_rotation = ProbTransform(A.RandomRotation(10), p=0.5)
        if opt.dataset == "cifar10":
            self.random_horizontal_flip = A.RandomHorizontalFlip(p=0.5)

    def forward(self, x):
        for module in self.children():
            x = module(x)
        return x

In [20]:
PostTensorTransform(hlpr.params).to(hlpr.params.device)

post_transforms = PostTensorTransform(IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD)

normalize = transforms.Normalize(IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD)

transform_train = transforms.Compose([transforms.ToTensor(), normalize,])
        
transform_test = transforms.Compose([transforms.ToTensor(), normalize])

train_dataset = torchvision.datasets.CIFAR10(
                        root="./data",
                        train=True,
                        download=True,
                        transform=transform_train)

train_loader = DataLoader(train_dataset,
                        batch_size=64,
                        shuffle=True,
                        num_workers=0)
test_dataset = torchvision.datasets.CIFAR10(
                        root="./data",
                        train=False,
                        download=True,
                        transform=transform_test)
test_loader = DataLoader(test_dataset,
                        batch_size=512,
                        shuffle=False, num_workers=0)

classes = ('plane', 'car', 'bird', 'cat',
            'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

clip_image = lambda x: torch.clamp(x, IMAGENET_MIN, IMAGENET_MAX)
target_transform = lambda x: torch.ones_like(x) * 8

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

In [ ]:
augmented_atkdata = post_transforms(atkdata)
augmented_data = post_transforms(data)